# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements_etl.txt ]; then pip install -r requirements_etl.txt; fi
    - name: Run ETL
      run: |
        python etl.py
        
    - name: Add email credential
      run: git config --global user.email "fernando.wittmann@gmail.com"
    - name: Add name as credential 
      run: git config --global user.name "Fernando Wittmann"
    - name: add remote url https://github.com/WittmannF/meli-challenge-leaderboard.git
      run: git remote set-url origin
    - name: check for changes
      run: git status
    - name: stage changed files
      run: git add .
    - name: commit changed files
      run: git commit -m "Auto updating CSV file"
    - name: fetch from master
      run: git fetch origin master
    - name: push code to master
      run: git push origin HEAD:master
