name: Master
on:
  push:
    branches:
      - master
  schedule:
    - cron: '* * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Run ETL
      run: |-
        python etl.py
